### ISSUE TITLE
Json Error Stacktrace

### ISSUE THREAD

**Issue by Max604** [minecrafter/SuperbVote#35] opened 2018-01-27 23:36 UTC
How do I solve this?

`[SuperbVote] Plugin SuperbVote v0.3.4 generated an exception while executing task 35160
java.lang.IncompatibleClassChangeError: Class io.minimum.minecraft.superbvote.storage.JsonVoteStorage does not implement the requested interface io.minimum.minecraft.superbvote.storage.VoteStorage
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-9b8bba4-bdcc7c7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by minecrafter** [comment] 2018-02-11 20:03
Duplicate of #34

**Closed by minecrafter** 2018-02-11 20:03 UTC
